RestaurantRaterBooking/Models/PostCategory.cs
namespace RestaurantRaterBooking.Models
{
    public class PostCategory
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public PostType PostType { get; set; }

        public ICollection<Blog>? Blog { get; set; }

        public ICollection<News>? News { get; set; }
    }

    public enum PostType
    {
        News,
        Blog
    }
}

RestaurantRaterBooking/Areas/Admin/Controllers/PostCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RestaurantRaterBooking.Models;

namespace RestaurantRaterBooking.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class PostCategoriesController : Controller
    {
        private readonly Models.AppContext _context;

        public PostCategoriesController(Models.AppContext context)
        {
            _context = context;
        }

        // GET: Admin/PostCategories
        public async Task<IActionResult> Index()
        {
              return _context.PostCategory != null ? 
                          View(await _context.PostCategory.ToListAsync()) :
                          Problem("Entity set 'AppContext.PostCategory'  is null.");
        }

        // GET: Admin/PostCategories/Create
        public IActionResult Create()
        {
            return View();
        }

		// POST: Admin/PostCategories/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Name, PostType")] PostCategory postCategory)
		{
			if (ModelState.IsValid)
			{
				_context.Add(postCategory);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}

			return View(postCategory);
		}

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.PostCategory == null)
            {
                return NotFound();
            }

            var postCategory = await _context.PostCategory.FindAsync(id);
            if (postCategory == null)
            {
                return NotFound();
            }
            return View(postCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name")] PostCategory postCategory)
        {
            if (id != postCategory.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(postCategory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostCategoryExists(postCategory.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(postCategory);
        }


        // POST: Admin/PostCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.PostCategory == null)
            {
                return Problem("Entity set 'AppContext.PostCategory'  is null.");
            }
            var postCategory = await _context.PostCategory.FindAsync(id);
            if (postCategory != null)
            {
                _context.PostCategory.Remove(postCategory);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostCategoryExists(Guid id)
        {
          return (_context.PostCategory?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

RestaurantRaterBooking/Controllers/PostCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RestaurantRaterBooking.Models;
using X.PagedList;

namespace RestaurantRaterBooking.Controllers
{
    public class PostCategoriesController : Controller
    {
        private readonly Models.AppContext _context;

        public PostCategoriesController(Models.AppContext context)
        {
            _context = context;
        }

        // GET: PostCategories
        public async Task<IActionResult> Index()
        {
              return _context.PostCategory != null ? 
                          View(await _context.PostCategory.ToListAsync()) :
                          Problem("Entity set 'AppContext.PostCategory'  is null.");
        }

        // GET: PostCategories/BlogDetails/5
        public async Task<IActionResult> BlogDetails(Guid? id, int? page)
        {
            if (id == null || _context.PostCategory == null)
            {
                return NotFound();
            }

            var postCategory = await _context.PostCategory
                .Include(b => b.Blog)
                .FirstOrDefaultAsync(m => m.Id == id && m.PostType == PostType.Blog);

            if (postCategory == null)
            {
                return NotFound();
            }

            // Lấy danh sách blogs
            var blogs = postCategory.Blog.AsQueryable();

            // Thiết lập phân trang
            int pageSize = 4; // Số lượng phần tử trên mỗi trang
            int pageNumber = (page ?? 1); // Số trang hiện tại, mặc định là 1 nếu không có giá trị

            // Tạo đối tượng IPagedList
            IPagedList<Blog> pagedBlogs = blogs.ToPagedList(pageNumber, pageSize);

            // Lưu vào ViewData
            ViewData["Blogs"] = pagedBlogs;

            ViewData["Categories"] = await _context.PostCategory.Where(n => n.PostType == PostType.Blog).ToListAsync();
            ViewData["Tags"] = await _context.Tag.Where(t => t.TagType == TagType.Blog).ToListAsync();

            return View(postCategory);
        }

        // GET: PostCategories/NewsDetails/5
        public async Task<IActionResult> NewsDetails(Guid? id, int? page)
        {
            if (id == null || _context.PostCategory == null)
            {
                return NotFound();
            }

            var postCategory = await _context.PostCategory
                .Include(b => b.News)
                .FirstOrDefaultAsync(m => m.Id == id && m.PostType == PostType.News);

            if (postCategory == null)
            {
                return NotFound();
            }

            // Lấy danh sách news
            var news = postCategory.News.AsQueryable();

            // Thiết lập phân trang
            int pageSize = 4; // Số lượng phần tử trên mỗi trang
            int pageNumber = (page ?? 1); // Số trang hiện tại, mặc định là 1 nếu không có giá trị

            // Tạo đối tượng IPagedList
            IPagedList<News> pagedNews = news.ToPagedList(pageNumber, pageSize);

            // Lưu vào ViewData
            ViewData["News"] = pagedNews;

            ViewData["Categories"] = await _context.PostCategory.Where(n => n.PostType == PostType.News).ToListAsync();
            ViewData["Tags"] = await _context.Tag.Where(t => t.TagType == TagType.News).ToListAsync();

            return View(postCategory);
        }

        public async Task<IActionResult> SearchBlog(string query, int? page)
        {
            if (string.IsNullOrWhiteSpace(query))
            {
                return NotFound();
            }

            // Tìm kiếm blogs có Title hoặc ShortContent chứa chuỗi query
            var blogs = _context.Blog
                .Where(b => b.Title.Contains(query) || b.ShortContent.Contains(query))
                .AsQueryable();

            // Thiết lập phân trang
            int pageSize = 4; // Số lượng phần tử trên mỗi trang
            int pageNumber = (page ?? 1); // Số trang hiện tại, mặc định là 1 nếu không có giá trị

            // Tạo đối tượng IPagedList
            IPagedList<Blog> pagedBlogs = blogs.ToPagedList(pageNumber, pageSize);

            // Lưu vào ViewData
            ViewData["Blogs"] = pagedBlogs;

            ViewData["Query"] = query;
            ViewData["Tags"] = await _context.Tag.Where(t => t.TagType == TagType.Blog).ToListAsync();
            ViewData["Categories"] = await _context.PostCategory.Where(n => n.PostType == PostType.Blog).ToListAsync();

            return View("SearchBlog", pagedBlogs);
        }

        public async Task<IActionResult> SearchNews(string query, int? page)
        {
            if (string.IsNullOrWhiteSpace(query))
            {
                return NotFound();
            }

            // Tìm kiếm blogs có Title hoặc ShortContent chứa chuỗi query
            var news = _context.News
                .Where(b => b.Title.Contains(query) || b.ShortContent.Contains(query))
                .AsQueryable();

            // Thiết lập phân trang
            int pageSize = 4; // Số lượng phần tử trên mỗi trang
            int pageNumber = (page ?? 1); // Số trang hiện tại, mặc định là 1 nếu không có giá trị

            // Tạo đối tượng IPagedList
            IPagedList<News> pagedNews = news.ToPagedList(pageNumber, pageSize);

            // Lưu vào ViewData
            ViewData["News"] = pagedNews;

            ViewData["Query"] = query;
            ViewData["Tags"] = await _context.Tag.Where(t => t.TagType == TagType.News).ToListAsync();
            ViewData["Categories"] = await _context.PostCategory.Where(n => n.PostType == PostType.News).ToListAsync();

            return View("SearchNews", pagedNews);
        }

        private bool PostCategoryExists(Guid id)
        {
          return (_context.PostCategory?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

RestaurantRaterBooking/Areas/Admin/Views/PostCategories/Index.cshtml
@model IEnumerable<RestaurantRaterBooking.Models.PostCategory>

@{
	ViewData["Title"] = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section head_scripts {
	<ul class="navbar-nav">
		<li class="nav-item">
			<a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
		</li>
		<li class="nav-item d-none d-sm-inline-block">
			<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
		</li>
		<li class="nav-item d-none d-sm-inline-block">
			<a class="nav-link"><i class="fas fa-angle-right"></i></a>
		</li>
		<li class="nav-item d-none d-sm-inline-block">
			<a asp-area="Admin" asp-controller="PostCategories" asp-action="Index" class="nav-link">Quản lý bài đăng</a>
		</li>
		<li class="nav-item d-none d-sm-inline-block">
			<a class="nav-link"><i class="fas fa-angle-right"></i></a>
		</li>
		<li class="nav-item d-none d-sm-inline-block">
			<a asp-area="Admin" asp-controller="PostCategories" asp-action="Index" class="nav-link">Danh mục bài đăng</a>
		</li>
	</ul>
}

<h1 class="text-center mb-2">Danh sách danh mục tin tức &amp; blog</h1>

<p>
	<a class="btn btn-primary ml-3" href="#" id="createPostCategory" data-toggle="modal" data-target="#createPostCategoryModal">Create New</a>
</p>

<table class="table">
	<thead>
		<tr>
			<th class="col-2">STT</th>
			<th class="col-3">Tên danh mục</th>
			<th class="col-4">Loại</th>
			<th class="col-3"></th>
		</tr>
	</thead>
	<tbody>
		@{
			int i = 1;
		}
		@foreach (var item in Model)
		{
			<tr>
				<th>@i</th>
				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.PostType)
				</td>
				<td class="text-center">
					<a class="btn btn-outline-success editButton"
					   data-toggle="modal"
					   data-target="#editPostCategoryModal"
					   data-id="@item.Id"
					   data-name="@item.Name"
					   data-posttype="@item.PostType">Edit</a>

					<a class="btn btn-outline-danger deleteButton" href="#" data-toggle="modal" data-target="#deleteConfirmationModal" data-id="@item.Id">Delete</a>
				</td>
			</tr>
			i++;
		}
	</tbody>
</table>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Modal for create -->
<div class="modal fade" id="createPostCategoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Create PostCategory</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<!-- Form goes here -->
				<form asp-action="Create" method="post">
					<div class="form-group">
						<label for="Name">Name</label>
						<input type="text" class="form-control" id="Name" name="Name" required>
					</div>
					<div class="form-group">
						<label for="PostType">Post Type</label>
						<select class="form-control" id="PostType" name="PostType" required>
							<option value="0">News</option>
							<option value="1">Blog</option>
						</select>
					</div>
					<div class="modal-footer">
					<button type="submit" class="btn btn-primary">Create</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<script>
	$(document).ready(function () {
		$("#createPostCategoryForm").submit(function (e) {
			e.preventDefault();

			var formData = {
				Name: $("#Name").val(),
				PostType: $("#PostType").val()
			};

			$.ajax({
				url: '@Url.Action("Create", "PostCategories")',
				type: 'POST',
				data: formData,
				success: function (data) {
					$('#createPostCategoryModal').modal('hide');
				},
				error: function (xhr, status, error) {
					console.error(xhr.responseText);
				}
			});
		});

		$("#createPostCategory").click(function () {
			$("#createPostCategoryForm")[0].reset();
		});
	});
</script>

<!-- Modal for Edit -->
<div class="modal fade" id="editPostCategoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Edit PostCategory</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form asp-action="Edit" method="post">
					<input type="hidden" id="editId" name="Id" />
					<div class="form-group">
						<label for="editName">Name</label>
						<input type="text" class="form-control" id="editName" name="Name" />
					</div>
					<div class="form-group">
						<label for="editPostType">Post Type</label>
						<div id="editPostType" class="form-control" readonly></div>
					</div>
					<div class="modal-footer">
						<button type="submit" class="btn btn-primary">Save Changes</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<script>
	$(document).ready(function () {
		$('.editButton').click(function () {
			var id = $(this).data('id');
			var name = $(this).data('name');
			var postType = $(this).data('posttype');

			// Cập nhật giá trị trong modal với dữ liệu cũ
			$('#editId').val(id);
			$('#editName').val(name);
			$('#editPostType').text(postType);
			$('#editPostCategoryModal').modal('show');
		});

		// Gửi POST request khi form được submit
		$('#editPostCategoryForm').submit(function (e) {
			e.preventDefault();

			var formData = {
				Id: $('#editId').val(),
				Name: $('#editName').val()
			};

			$.ajax({
				type: 'POST',
				url: '/PostCategories/Edit',
				data: formData,
				success: function (data) {
					// Xử lý sau khi chỉnh sửa thành công
					$('#editPostCategoryModal').modal('hide');
					location.reload();
				},
				error: function (xhr, status, error) {
					// Xử lý khi có lỗi
					console.error(xhr.responseText);
				}
			});
		});
	});
</script>

<!-- Modal for delete -->
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="deleteConfirmationModalLabel">Xác nhận xóa</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				Bạn có chắc chắn muốn xóa nhà hàng này không?
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
				<button type="button" class="btn btn-danger" id="confirmDeleteButton">Xóa</button>
			</div>
		</div>
	</div>
</div>

<script>
	var restaurantIdToDelete;

	$(document).ready(function () {
		// Hiển thị modal xóa nhà hàng
		$('.deleteButton').click(function () {
			restaurantIdToDelete = $(this).data('id');
			$('#deleteConfirmationModal').modal('show');
		});

		// Xóa nhà hàng khi nhấn nút "Xóa" trên modal
		$('#confirmDeleteButton').click(function () {
			var url = '/Admin/PostCategories/Delete/' + restaurantIdToDelete;

			$.ajax({
				type: "POST",
				url: url,
				headers: {
					RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val()
				},
				success: function (data) {
					// Xử lý khi xóa thành công
					alert("Đã xóa thành công");
					location.reload();
				},
				error: function (data) {
					// Xử lý khi xóa thất bại
					alert("Xóa thất bại");
				}
			});
		});
	});
</script>